#!/usr/bin/env bash

set -eo pipefail

# If config file does not exist, try to register the instance

echo "Start of nimble register"

if [ -f /usr/bin/nimble_regutil ]; then
    echo "nimble_regutil installed"
fi

if ! [ -f /etc/nimble/nimble.conf ]; then

    # Need username and password to register
    if ! [ -z "$WMSPANEL_USER" ]; then

        if [ ! -d /etc/nimble ];
            echo "/etc/nimble don't exist"
            mkdir /etc/nimble
        fi
        
        if [ -d /etc/nimble.conf/ ]; then
            cp -fr /etc/nimble.conf/* /etc/nimble/
        else
            echo "/etc/nimble.conf/ don't exist"
        fi    
        
        ARGS=""
        if ! [ -z "$WMSPANEL_SLICES" ]; then
            ARGS="--slices=$WMSPANEL_SLICES"
        fi

        # Try to register with apply-rules
        if ! /usr/bin/nimble_regutil $ARGS --apply-rules-conf \
             -u "$WMSPANEL_USER" -p "$WMSPANEL_PASS"; then
            # Try without apply-rules
            if ! /usr/bin/nimble_regutil $ARGS --apply-rules-conf \
                 -u "$WMSPANEL_USER" -p "$WMSPANEL_PASS"; then
                # Not able to register; remove config again
                rm -f /etc/nimble/nimble.conf
            fi
        fi
    fi
    if ! [ -z "$WMSPANEL_TOKEN" ]; then          
    ## Andrey Leb -- add 8082 port and password
        echo "### managment port" | /usr/bin/tee -a /etc/nimble/nimble.conf
        echo "management_listen_interfaces = *" | /usr/bin/tee -a /etc/nimble/nimble.conf
        echo "management_token = $WMSPANEL_TOKEN" | /usr/bin/tee -a /etc/nimble/nimble.conf
        echo "management_port = 8082" | /usr/bin/tee -a /etc/nimble/nimble.conf
        # cat /etc/nimble/nimble.conf
    fi
fi

echo "End of nimble register"

chown -R nimble:root /etc/nimble
chown -R nimble:root /var/cache/nimble
rm -f /etc/nimble/run_as_root
